server:
  port: 3000
  
# default:
#     type: 'mongodb'
#     url: 'mongodb://35.224.45.227:27017/pranav_dixit'
#     username: 'pranav_dixit'
#     password: 'pranav_dixit'
#     database: "pranav_dixit"
#     entities: ["dist/**/*.entity{.ts,.js}"]
#     logging: ["query","error"]
#     logger: "file"
#     extra: { timezone: "+5:30" }
#     useUnifiedTopology: true
#     synchronize: true
